name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: testGetDistancePrint1
      id: testgetdistanceprint1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testGetDistancePrint1
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "TestDNA.testGetDistancePrint1"
        timeout: 10
        max-score: 4
    - name: testGetDistancePrint2
      id: testgetdistanceprint2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testGetDistancePrint2
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "TestDNA.testGetDistancePrint2"
        timeout: 10
        max-score: 4
    - name: testDNAGetDistance
      id: testdnagetdistance
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testDNAGetDistance
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "TestDNA.testGetDistance"
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTGETDISTANCEPRINT1_RESULTS: "${{steps.testgetdistanceprint1.outputs.result}}"
        TESTGETDISTANCEPRINT2_RESULTS: "${{steps.testgetdistanceprint2.outputs.result}}"
        TESTDNAGETDISTANCE_RESULTS: "${{steps.testdnagetdistance.outputs.result}}"
      with:
        runners: testgetdistanceprint1,testgetdistanceprint2,testdnagetdistance
